name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - run: poetry install
      - run: poetry run pytest --cov
      - run: poetry run flake8 .
      - run: poetry run black .
      - run: poetry run isort .
