name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - run: pip install poetry==1.1.11
      - run: poetry run pytest --cov
      - run: poetry run flake8 .
      - run: poetry run black .
      - run: poetry run isort .
