name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11

      - run: poetry install
      - run: pip install nox==2020.8.22
      - run: nox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: unittests
